### ISSUE TITLE
Checking Restaurants API for CORS Errors

### ISSUE THREAD

**Issue by avidrunner87** [avidrunner87/small-talk#16]
AS A team member
I WANT to view local location restaurants
SO THAT I can see whats hitting the charts for a location

**Comment by acromarti01** [comment]
CORS error checked
using TripAdvisor   https://rapidapi.com/apidojo/api/travel-advisor/
Need longitude and latitude of the city

**Comment by avidrunner87** [comment]
@acromarti01, not a problem. With each location we grab the latitude and longitude.
